### ISSUE TITLE
Add Contributor Guidelines to the repo

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#57]
Per our "mergingdocs" convo (😂), it would be great to add contributor guidelines to the repo to establish best practices for event attendees and other to submit feedback and changes

**Comment by dcwalk** [comment]
Notes from a quick convo with @khdelphine RE this, the guidelines could contain:
- [x] Bite-sized changes [Done]
- [x] Make clear who reviews/merges in PRs [Done]
- [x] Best way to receive event feedback/suggestions [We should add something about the possibility of creating issues]

**Comment by khdelphine** [comment]
Mostly done, but a few details to be finalized.

**Comment by dcwalk** [comment]
As a point of etiquette-- can we confirm whether we are using the review feature and if someone is pinged for review that they should before a merge happens?

**Comment by khdelphine** [comment]
@dcwalk: what would you recommend? 

Certainly for external people submitting PRs, we should make sure the review process happens properly.

For small internal PRs, I am not sure. I often find myself with very small changes that I know are not going to be controversial, and that I feel anxious to get out (e.g., because the fix something broken or messy). Also I feel that when there is an accumulation of PRs, things can become confusing in Github (for me at least), which makes me want to move them through. Do you think it is better to proceed more slowly and make sure every PR is systematically reviewed properly? And second question: is it ok to not name a reviewer if the PR is particularly non-controversial? (In such cases, @rlappel whose desk is 5 feet away from mine tends to be the one who merges my PRs.) Or do you think we should make the review process an unskippable priority?

**Comment by dcwalk** [comment]
This looks almost done except for #74, once #86 lands I believe we can close this?

**Comment by dcwalk** [comment]
Closed via #86
